backend:
  name: git-gateway
  branch: main
media_folder: uploads
public_folder: /uploads
collections:
  - name: watches
    label: Watches
    folder: content/watches
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Video', name: 'video', widget: 'file', required: false }
      - { label: 'WhatsApp Link', name: 'whatsapp', widget: 'string' }